{% set version = "0.11.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-snakecase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/snakecase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/snakecase/snakecase_{{ version }}.tar.gz
  sha256: 2a5f9791337ca42e392f23fb873eb44f74810583e9aa7c62fda2f28f9e750821

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-stringi
    - r-stringr
  run:
    - r-base
    - r-stringi
    - r-stringr

test:
  commands:
    - $R -e "library('snakecase')"           # [not win]
    - "\"%R%\" -e \"library('snakecase')\""  # [win]

about:
  home: https://github.com/Tazinho/snakecase
  license: GPL-3.0-only
  summary: A consistent, flexible and easy to use tool to parse and convert strings into cases like snake or camel among others.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: snakecase
# Version: 0.11.0
# Date: 2019-05-25
# Title: Convert Strings into any Case
# Description: A consistent, flexible and easy to use tool to parse and convert strings into cases like snake or camel among others.
# Authors@R: c( person("Malte", "Grosser", , "malte.grosser@gmail.com", role = c("aut", "cre")))
# Maintainer: Malte Grosser <malte.grosser@gmail.com>
# Depends: R (>= 3.2)
# Imports: stringr, stringi
# Suggests: testthat, covr, tibble, purrrlyr, knitr, rmarkdown, magrittr
# URL: https://github.com/Tazinho/snakecase
# BugReports: https://github.com/Tazinho/snakecase/issues
# Encoding: UTF-8
# License: GPL-3
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-05-25 21:16:42 UTC; MGO
# Author: Malte Grosser [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-05-25 22:50:03 UTC
