travis:
  secure:
    BINSTAR_TOKEN: xVY1mRrP2ya5Ol6z55haw5UeHMLoCRB7fVwYEo6eezKeuVMHCb4QFskvVVXUMw5T1u0ACgIjPUqyWdmMjQqPt+Fb89yoQU4LgmIqfpjt9QNbaoWLtNpm77bbuUZBuKRzilYyqt/5X2QuRP8zT1/4ug8GseIFQQObHQdzRVxO5UxNmx2ETTHR3WnSD0moAeOeBNseheOjZ14KTsXww37q1ZBQznmh5zIm+QFclRuwraVhReryc9gdAEUb5sqiY5EZ4Lr1Dy6B1l70xU8KYmvcwXc4pE3LklzZ10UAcDxscALMSF3JZHsBGzDvnfVb71ud8OJHm1SXEdqO/0jYh8sBEKyprF8EKhaAjX/7SVIHuYxbi/5Bk0pZ26ObErhXqdhFlq4VQxmLveRsNKRfN9ZiVXhGhONFZ4gWFMN5XZHfxoYuKFNJtzDcSen23lUANIfJDcydwwJA02i0eMT/FrJ54bc5oQwsx4ud0fDq3lpuSCWuReiSzz5xm6wKlRh/Ceh6P5luopewQjghZmRYWdWWZlmcqSqfR0FWbmhNLc+bz3G1Oaz5NP1UZq7mZDeNrkD1LBVyojzvuTB8Kg4g5hVFJonArOU55Ic3KdOfXUv3z+N957o+btK37fzzu3K3b/vWvIMT1k6fBHh8CQWZUYkV7hQiAmu8Gn9ot/XI3pJ2Ao8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
