travis:
  secure:
    BINSTAR_TOKEN: xFmZE5CoN0o/R8hUqAZoqC73jKNKpunae5frKf3c+Oim1kg/7OAUTAgH6vmApNl6LUeUsQFzb1lKZCM0O6oyHErEL5soKvoYa+TVM5O0imDqJMtNVoVSDJ2XArsLtaUTDo0eam4YNd799npsN8jvmrEhFZy4D5tRplFBqWofjkTK4rRCGmHGqljH86l/xrrL7blKN0BIPrZh5KbAQ02oPI10/Ohmu48gIon1RlFU/HKs/1gUbDDM25auhE6/2TsJFjFKQ1Nk+DfWQYTKkQ+mvZQmR2icqnchxXWSe3EsJK4GER4weSCCJqJtne6fqZjEq51DH2Kt1ZrUi1J97c+rgDDHJI1AufTU4ePOgwK3Okqxha1cDk/+uq1lS831dEZPvoNIR07AqgQWf5ca4n8WHEY5cOl6h+fkbvocYhuyRr0rJOJlU08r9cLVBOEHkvVfNn3GWNvdwNhijd7TNWUH8UkCmTEz6F9zBUybwVwtdV595NFyAcdfcLsmnST+QccQn6F2OcLV36nmS1kghjCl6zdlCTe30tt9y1LAk/An1oNVZb5rZWsgBpCQi/gE1wpcaaHQlgsG9QazGv09r8rPfncBnZK3YAjg7vM8h6M2m8UR2+f5mBhULkueSVzY2HlAT3J1Fh00rgfREIDQPmWliolJRhS/4FTX2HNLrnFr5Fk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
