travis:
  secure:
    BINSTAR_TOKEN: na1H+7mb8Uq5W3R8LJMR+zVllxJyCCHxvIJGRqmDuC4ur/+68sUJlZ8L+A1PUg/2V+sGpOIJsmmvVcO7E3nqz5iAS6hT52z8T90RfZwUDmY5NYHljwBXu0ISpVhqjgcjxMNt4idpCjvpmAata1EIWQnlbdT8G/uEZYBWy3kZ8vxXvqNEwnj/QMBWP4/k+uVO2aV6kCTaMAL/gMP3x27ajezdbIBxolHceDodi54CNk6aSeTE3ZddtPSk5dtQcY04mWc0YuU7yMTqRkWBRxdhvAyPzhY66IUCwshlIR4arTLnP70FHOLUYdr+919KlzIXSnKgAULEDHo9zY9L3b/yU35oTnxiZxmo9qDVRaj55gBhsySu9PQhlwbJ8IKtVqm6CQyAlrN/sNKQLtzpSSp2D0CVRJVlDwkUlqn2bDKpxPlzcQMwvwyy2me0Vzv2WqhRlQCBFxr6iEhe6vKQD7hgjO7ELxc6iAA8jPVjpcIR6coYEeabTFFps60VFpDggdxpPGFFYbO79u7wPW+N1VOjwHnIBtCwSFWUBiVt8ZjpTc/QRWL3RlGDBC1oPwqlRoiDIJ38J0h2WwJh8/6HV14u1mf/15kp1+DtSsE5pEjxbt2QUWR8nkr1IXPa6Ya8kaD6gbX1QTveF+p6CxSczIfmBoaXWOkHLZJaaeGjpMONRzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
