travis:
  secure:
    BINSTAR_TOKEN: WfbDMgXM2J113ouIq113OzwSTKOBAJxBg1Kz/qPAJi+DZ86AGP4Yp15QKgpKzfZfYQFVeP7D8J6DM8pt24kwtTRpTBXzDqqpw03cSPK7Bdv+acSJit8mAv5F/i6+sKPW2w+GItQHdDQCKjOcSZ+rXHFIB3clGuP7lgp7CI1P4LN8ud8Xgg+bigWDdUuOZmFAZBEkqimq02ad8er58u+S4HSDR869s3wu2J4gjcfVuEqSUwRU5Pon7VmyYsu8lYVUGnemdxc3t5unj/OcgH7cIM4HENAJWa/IPwH8OyHjH4xybeZhQv88+QlO3o2aOJhiM4r3JGGUUnNy84WbdesZwPqU4xWbnAH9Ydf7vlqCTEpMx5jG3/ccga+zLUJF78vZeRI7F/L+JXN3SgaA429ANQI6+zErc56fMtfMaA28gg8e6NuiDA50P9YTTaOLnkS/Jy3H8/wUcqIQCHPdRnxqNTzOjw9brG9/Gsd3WHqRmz5XZjDx4+FMi2myEesKPBPbIbkRB+O1giKqehsoHIxnxv7pEHOlkwM0GEEeHctOvY/3eTW89uDq+FojgF04HznIrLHsEREpDTVAIQQ9vgfNfcIaBowljaeZcfHXHzkpQVvm9tomsBa7U7Zst6e3860wEs9dzrbM04rGGHl1UKaSz/3/+0KquWxO3FTGODqYRJw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
